[project]
name = 'tokenized-rare-earth-mineral-trading'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.mineral-token]
path = 'contracts/mineral-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.supply-tracker]
path = 'contracts/supply-tracker.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
